import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";
import {
  Loader2, Plus, Pencil, Trash2, Download, FileText, Stethoscope,
  ChevronDown, ChevronUp, ClipboardList, Pill, AlertCircle, CheckCircle2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { ClinicalRecord } from "@shared/schema";

const DIAGNOSIS_TAGS = [
  "Caries", "Gingivitis", "Periodontitis", "Pulpitis", "Abscess",
  "Fracture", "Sensitivity", "Malocclusion", "Impaction", "TMJ",
  "Bruxism", "Dry Socket", "Oral Ulcer", "Calculus", "Recession",
];

function generatePrescriptionPDF(record: ClinicalRecord, clinicName?: string) {
  import("jspdf").then(({ default: jsPDF }) => {
    const doc = new jsPDF();
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    const line = () => { doc.setDrawColor(200, 200, 200); doc.line(margin, y, pageW - margin, y); y += 6; };

    doc.setFillColor(62, 52, 180);
    doc.rect(0, 0, pageW, 38, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(clinicName || "Clinic", margin, 16);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Clinical Record / Prescription", margin, 26);
    doc.text(`Date: ${format(new Date(record.createdAt!), "MMM d, yyyy")}`, margin, 34);

    y = 50;
    doc.setTextColor(30, 28, 60);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Patient Information", margin, y); y += 8;
    line();
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Name: ${record.patientName}`, margin, y); y += 7;
    if (record.patientPhone) { doc.text(`Phone: ${record.patientPhone}`, margin, y); y += 7; }
    if (record.doctorName) { doc.text(`Attending Doctor: ${record.doctorName}`, margin, y); y += 7; }
    y += 4;

    if (record.diagnosis && record.diagnosis.length > 0) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Diagnosis", margin, y); y += 8;
      line();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(record.diagnosis.join(", "), margin, y, { maxWidth: pageW - margin * 2 });
      y += 14;
    }

    if (record.prescription) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Prescription", margin, y); y += 8;
      line();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      const lines = doc.splitTextToSize(record.prescription, pageW - margin * 2);
      doc.text(lines, margin, y);
      y += lines.length * 6 + 8;
    }

    if (record.notes) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Clinical Notes", margin, y); y += 8;
      line();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      const lines = doc.splitTextToSize(record.notes, pageW - margin * 2);
      doc.text(lines, margin, y);
    }

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by BookMySlot · Confidential Medical Record", margin, doc.internal.pageSize.getHeight() - 10);

    doc.save(`prescription_${record.patientName.replace(/\s+/g, "_")}_${format(new Date(record.createdAt!), "yyyyMMdd")}.pdf`);
  });
}

interface ClinicalRecordsTabProps {
  bookingId: number;
  clinicId: number;
  patientName: string;
  patientPhone?: string | null;
  doctorName?: string | null;
  mode: "doctor" | "admin";
  clinicName?: string;
}

export default function ClinicalRecordsTab({
  bookingId, clinicId, patientName, patientPhone, doctorName, mode, clinicName,
}: ClinicalRecordsTabProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [diagnosisDraft, setDiagnosisDraft] = useState<string[]>([]);
  const [prescriptionDraft, setPrescriptionDraft] = useState("");
  const [notesDraft, setNotesDraft] = useState("");
  const [doctorNameDraft, setDoctorNameDraft] = useState(doctorName || "");

  const queryKey = ["/api/clinical-records/booking", bookingId];

  const { data: records = [], isLoading, error } = useQuery<ClinicalRecord[]>({
    queryKey,
    queryFn: async () => {
      const res = await fetch(`/api/clinical-records/booking/${bookingId}`, { credentials: "include" });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.message || `Error ${res.status}`);
      }
      return res.json();
    },
  });

  const createMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/clinical-records", {
        bookingId, clinicId, patientName,
        patientPhone: patientPhone || null,
        doctorName: doctorNameDraft || doctorName || null,
        diagnosis: diagnosisDraft,
        prescription: prescriptionDraft || null,
        notes: notesDraft || null,
      });
      if (!res.ok) { const b = await res.json(); throw new Error(b.message); }
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey });
      toast({ title: "Record saved", description: "Clinical record added successfully." });
      resetForm();
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const updateMutation = useMutation({
    mutationFn: async (id: number) => {
      const res = await apiRequest("PATCH", `/api/clinical-records/${id}`, {
        doctorName: doctorNameDraft || doctorName || null,
        diagnosis: diagnosisDraft,
        prescription: prescriptionDraft || null,
        notes: notesDraft || null,
      });
      if (!res.ok) { const b = await res.json(); throw new Error(b.message); }
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey });
      toast({ title: "Record updated" });
      resetForm();
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: number) => {
      const res = await apiRequest("DELETE", `/api/clinical-records/${id}`, {});
      if (!res.ok) { const b = await res.json(); throw new Error(b.message); }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey });
      toast({ title: "Record deleted" });
    },
    onError: (e: any) => toast({ title: "Error", description: e.message, variant: "destructive" }),
  });

  const resetForm = () => {
    setShowForm(false);
    setEditingId(null);
    setDiagnosisDraft([]);
    setPrescriptionDraft("");
    setNotesDraft("");
    setDoctorNameDraft(doctorName || "");
  };

  const startEdit = (record: ClinicalRecord) => {
    setEditingId(record.id);
    setDiagnosisDraft(record.diagnosis || []);
    setPrescriptionDraft(record.prescription || "");
    setNotesDraft(record.notes || "");
    setDoctorNameDraft(record.doctorName || doctorName || "");
    setShowForm(true);
  };

  const toggleTag = (tag: string) => {
    setDiagnosisDraft(prev =>
      prev.includes(tag) ? prev.filter(t => t !== tag) : [...prev, tag]
    );
  };

  const latestRecord = records[0] ?? null;
  const historyRecords = records.slice(1);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-8">
        <Loader2 className="h-5 w-5 animate-spin text-primary" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center gap-2 py-6 text-center rounded-xl border border-dashed border-destructive/40 bg-destructive/5">
        <p className="text-xs font-medium text-destructive">Failed to load records</p>
        <p className="text-[10px] text-muted-foreground">{(error as Error).message}</p>
      </div>
    );
  }

  return (
    <div className="space-y-3">

      {/* ── Latest Record ── */}
      {latestRecord ? (
        <div className="rounded-xl border border-primary/25 bg-primary/3 overflow-hidden">
          <div className="px-3 py-2 bg-primary/8 border-b border-primary/15 flex items-center justify-between gap-2">
            <div className="flex items-center gap-1.5">
              <ClipboardList className="h-3 w-3 text-primary" />
              <span className="text-[10px] font-bold uppercase tracking-wider text-primary">Latest Record</span>
              <span className="text-[9px] text-primary/60 font-medium">
                {format(new Date(latestRecord.createdAt!), "MMM d, yyyy · h:mm a")}
              </span>
            </div>
            <div className="flex items-center gap-1.5">
              <Button
                size="sm"
                variant="outline"
                className="h-6 px-2 text-[10px] gap-1 border-primary/30 text-primary hover:bg-primary/10"
                onClick={() => generatePrescriptionPDF(latestRecord, clinicName)}
                data-testid="button-download-latest-pdf"
              >
                <Download className="h-2.5 w-2.5" />
                PDF
              </Button>
              {mode === "doctor" && (
                <>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-6 px-2 text-[10px] gap-1 text-muted-foreground hover:text-primary"
                    onClick={() => startEdit(latestRecord)}
                    data-testid="button-edit-latest-record"
                  >
                    <Pencil className="h-2.5 w-2.5" />
                    Edit
                  </Button>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-6 px-2 text-[10px] gap-1 text-muted-foreground hover:text-destructive"
                    onClick={() => deleteMutation.mutate(latestRecord.id)}
                    disabled={deleteMutation.isPending}
                    data-testid="button-delete-latest-record"
                  >
                    <Trash2 className="h-2.5 w-2.5" />
                  </Button>
                </>
              )}
            </div>
          </div>
          <div className="px-3 py-2.5 space-y-2">
            {latestRecord.doctorName && (
              <p className="text-[10px] text-muted-foreground flex items-center gap-1">
                <Stethoscope className="h-3 w-3" />
                Dr. {latestRecord.doctorName}
              </p>
            )}
            {latestRecord.diagnosis && latestRecord.diagnosis.length > 0 && (
              <div>
                <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Diagnosis</p>
                <div className="flex flex-wrap gap-1">
                  {latestRecord.diagnosis.map(d => (
                    <Badge key={d} variant="outline" className="text-[10px] px-2 py-0.5 rounded-full border-primary/30 bg-primary/8 text-primary font-semibold">
                      {d}
                    </Badge>
                  ))}
                </div>
              </div>
            )}
            {latestRecord.prescription && (
              <div>
                <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1 flex items-center gap-1">
                  <Pill className="h-3 w-3" /> Prescription
                </p>
                <p className="text-xs text-foreground leading-relaxed whitespace-pre-line">{latestRecord.prescription}</p>
              </div>
            )}
            {latestRecord.notes && (
              <div>
                <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1 flex items-center gap-1">
                  <FileText className="h-3 w-3" /> Notes
                </p>
                <p className="text-xs text-muted-foreground leading-relaxed whitespace-pre-line">{latestRecord.notes}</p>
              </div>
            )}
          </div>
        </div>
      ) : (
        <div className="flex flex-col items-center gap-2 py-6 text-center rounded-xl border border-dashed border-border/60 bg-muted/10">
          <ClipboardList className="h-7 w-7 text-muted-foreground/30" />
          <p className="text-xs font-medium text-muted-foreground">No clinical records yet</p>
          {mode === "doctor" && (
            <p className="text-[10px] text-muted-foreground/70">Add the first record for this patient below</p>
          )}
        </div>
      )}

      {/* ── History ── */}
      {historyRecords.length > 0 && (
        <div className="rounded-xl border border-border/60 bg-muted/10 overflow-hidden">
          <div className="px-3 py-2 bg-muted/30 border-b border-border/40 flex items-center gap-1.5">
            <FileText className="h-3 w-3 text-muted-foreground" />
            <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
              History ({historyRecords.length})
            </span>
          </div>
          <div className="divide-y divide-border/30">
            {historyRecords.map(record => (
              <div key={record.id} className="px-3 py-2">
                <button
                  className="w-full flex items-center justify-between gap-2 text-left"
                  onClick={() => setExpandedId(expandedId === record.id ? null : record.id)}
                >
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] text-muted-foreground font-medium">
                      {format(new Date(record.createdAt!), "MMM d, yyyy")}
                    </span>
                    {record.diagnosis && record.diagnosis.length > 0 && (
                      <span className="text-[10px] text-primary/70 font-semibold">{record.diagnosis.slice(0, 2).join(", ")}{record.diagnosis.length > 2 ? "…" : ""}</span>
                    )}
                  </div>
                  <div className="flex items-center gap-1.5 shrink-0">
                    <Button
                      size="sm"
                      variant="ghost"
                      className="h-5 px-1.5 text-[9px] gap-1 text-muted-foreground hover:text-primary"
                      onClick={e => { e.stopPropagation(); generatePrescriptionPDF(record, clinicName); }}
                    >
                      <Download className="h-2.5 w-2.5" />
                    </Button>
                    {expandedId === record.id ? <ChevronUp className="h-3 w-3 text-muted-foreground" /> : <ChevronDown className="h-3 w-3 text-muted-foreground" />}
                  </div>
                </button>
                {expandedId === record.id && (
                  <div className="mt-2 space-y-1.5 animate-in slide-in-from-top-1 duration-150">
                    {record.doctorName && <p className="text-[10px] text-muted-foreground flex items-center gap-1"><Stethoscope className="h-2.5 w-2.5" />Dr. {record.doctorName}</p>}
                    {record.diagnosis && record.diagnosis.length > 0 && (
                      <div className="flex flex-wrap gap-1">
                        {record.diagnosis.map(d => (
                          <Badge key={d} variant="outline" className="text-[9px] px-1.5 py-0 rounded-full border-primary/20 bg-primary/5 text-primary">{d}</Badge>
                        ))}
                      </div>
                    )}
                    {record.prescription && <p className="text-[10px] text-foreground leading-relaxed whitespace-pre-line">{record.prescription}</p>}
                    {record.notes && <p className="text-[10px] text-muted-foreground leading-relaxed whitespace-pre-line">{record.notes}</p>}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Add / Edit Form (doctor only) ── */}
      {mode === "doctor" && (
        <>
          {!showForm ? (
            <Button
              size="sm"
              variant="outline"
              className="w-full h-8 text-xs gap-1.5 border-dashed border-primary/40 text-primary hover:bg-primary/5"
              onClick={() => { resetForm(); setShowForm(true); }}
              data-testid="button-add-clinical-record"
            >
              <Plus className="h-3.5 w-3.5" />
              Add Clinical Record
            </Button>
          ) : (
            <div className="rounded-xl border border-primary/30 bg-primary/3 overflow-hidden animate-in slide-in-from-top-1 duration-200">
              <div className="px-3 py-2 bg-primary/8 border-b border-primary/15 flex items-center gap-1.5">
                <Plus className="h-3 w-3 text-primary" />
                <span className="text-[10px] font-bold uppercase tracking-wider text-primary">
                  {editingId ? "Edit Record" : "New Clinical Record"}
                </span>
              </div>
              <div className="px-3 py-3 space-y-3">
                {/* Doctor name */}
                <div>
                  <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Doctor Name</Label>
                  <Input
                    value={doctorNameDraft}
                    onChange={e => setDoctorNameDraft(e.target.value)}
                    placeholder="Dr. ..."
                    className="h-8 text-xs mt-1"
                    data-testid="input-doctor-name"
                  />
                </div>

                {/* Diagnosis tags */}
                <div>
                  <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Diagnosis</Label>
                  <div className="flex flex-wrap gap-1.5 mt-1.5">
                    {DIAGNOSIS_TAGS.map(tag => (
                      <button
                        key={tag}
                        type="button"
                        onClick={() => toggleTag(tag)}
                        className={`text-[10px] px-2.5 py-1 rounded-full border font-semibold transition-all ${
                          diagnosisDraft.includes(tag)
                            ? "bg-primary text-white border-primary"
                            : "border-border/60 text-muted-foreground hover:border-primary/50 hover:text-primary"
                        }`}
                        data-testid={`tag-diagnosis-${tag.toLowerCase()}`}
                      >
                        {tag}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Prescription */}
                <div>
                  <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                    Prescription <span className="text-muted-foreground/60 normal-case">(medicines, dosage, duration)</span>
                  </Label>
                  <Textarea
                    value={prescriptionDraft}
                    onChange={e => setPrescriptionDraft(e.target.value)}
                    placeholder="e.g. Amoxicillin 500mg — 1 tab TID × 5 days&#10;Ibuprofen 400mg — 1 tab BD × 3 days"
                    className="text-xs mt-1 min-h-[80px] resize-none"
                    data-testid="textarea-prescription"
                  />
                </div>

                {/* Notes */}
                <div>
                  <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                    Clinical Notes <span className="text-muted-foreground/60 normal-case">(optional)</span>
                  </Label>
                  <Textarea
                    value={notesDraft}
                    onChange={e => setNotesDraft(e.target.value)}
                    placeholder="Observations, next steps, follow-up instructions…"
                    className="text-xs mt-1 min-h-[60px] resize-none"
                    data-testid="textarea-clinical-notes"
                  />
                </div>

                <div className="flex gap-2 pt-1">
                  <Button
                    size="sm"
                    className="flex-1 h-8 text-xs font-bold"
                    onClick={() => editingId ? updateMutation.mutate(editingId) : createMutation.mutate()}
                    disabled={createMutation.isPending || updateMutation.isPending || (diagnosisDraft.length === 0 && !prescriptionDraft)}
                    data-testid="button-save-clinical-record"
                  >
                    {(createMutation.isPending || updateMutation.isPending) ? (
                      <Loader2 className="h-3 w-3 animate-spin" />
                    ) : (
                      <><CheckCircle2 className="h-3 w-3 mr-1" />{editingId ? "Update" : "Save Record"}</>
                    )}
                  </Button>
                  <Button size="sm" variant="ghost" className="h-8 text-xs" onClick={resetForm}>
                    Cancel
                  </Button>
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
