/**
 * Visual reference information for the permanent FDI tooth chart.
 *
 * These are relative illustration settings, not measurements of a patient's
 * teeth and not clinical findings. Later drawing work can use this one source
 * of truth without changing the saved chart data.
 */

export type OdontogramArch = "upper" | "lower";
export type OdontogramSide = "right" | "left";
export type OdontogramQuadrant = "Q1" | "Q2" | "Q3" | "Q4";
export type OdontogramToothType = "incisor" | "canine" | "premolar" | "molar";
export type OdontogramCuspPattern =
  | "smooth"
  | "single-cusp"
  | "two-cusp"
  | "upper-molar"
  | "lower-molar"
  | "variable";
export type OdontogramRootCurve = "neutral" | "toward-midline" | "away-from-midline";

export interface OdontogramToothReference {
  number: number;
  displayName: string;
  arch: OdontogramArch;
  side: OdontogramSide;
  quadrant: OdontogramQuadrant;
  type: OdontogramToothType;
  crownWidth: number;
  crownHeight: number;
  rootLength: number;
  rootCount: 1 | 2 | 3;
  cuspCount: number;
  cuspPattern: OdontogramCuspPattern;
  hasPointedCusp: boolean;
  hasTwoCusps: boolean;
  hasMolarRidge: boolean;
  rootCurve: OdontogramRootCurve;
}

/**
 * The order is from left to right as the doctor sees the chart:
 *
 * Q1 | Q2
 * Q4 | Q3
 *
 * The FDI number remains the clinical identifier; this order only controls
 * where each tooth is displayed on screen.
 */
export const TOOTH_DISPLAY_ORDER = {
  upperRight: [18, 17, 16, 15, 14, 13, 12, 11],
  upperLeft: [21, 22, 23, 24, 25, 26, 27, 28],
  lowerRight: [48, 47, 46, 45, 44, 43, 42, 41],
  lowerLeft: [31, 32, 33, 34, 35, 36, 37, 38],
} as const;

export const TOOTH_REFERENCE: Record<number, OdontogramToothReference> = {
  // Q1 — upper right
  11: {
    number: 11,
    displayName: "UR Central",
    arch: "upper",
    side: "right",
    quadrant: "Q1",
    type: "incisor",
    crownWidth: 1,
    crownHeight: 1,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 0,
    cuspPattern: "smooth",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  12: {
    number: 12,
    displayName: "UR Lateral",
    arch: "upper",
    side: "right",
    quadrant: "Q1",
    type: "incisor",
    crownWidth: 0.85,
    crownHeight: 1,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 0,
    cuspPattern: "smooth",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  13: {
    number: 13,
    displayName: "UR Canine",
    arch: "upper",
    side: "right",
    quadrant: "Q1",
    type: "canine",
    crownWidth: 0.95,
    crownHeight: 1.1,
    rootLength: 1.4,
    rootCount: 1,
    cuspCount: 1,
    cuspPattern: "single-cusp",
    hasPointedCusp: true,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  14: {
    number: 14,
    displayName: "UR 1st PM",
    arch: "upper",
    side: "right",
    quadrant: "Q1",
    type: "premolar",
    crownWidth: 1,
    crownHeight: 0.9,
    rootLength: 1.2,
    rootCount: 2,
    cuspCount: 2,
    cuspPattern: "two-cusp",
    hasPointedCusp: false,
    hasTwoCusps: true,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  15: {
    number: 15,
    displayName: "UR 2nd PM",
    arch: "upper",
    side: "right",
    quadrant: "Q1",
    type: "premolar",
    crownWidth: 0.95,
    crownHeight: 0.9,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 2,
    cuspPattern: "two-cusp",
    hasPointedCusp: false,
    hasTwoCusps: true,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  16: {
    number: 16,
    displayName: "UR 1st Molar",
    arch: "upper",
    side: "right",
    quadrant: "Q1",
    type: "molar",
    crownWidth: 1.2,
    crownHeight: 0.8,
    rootLength: 1.1,
    rootCount: 3,
    cuspCount: 4,
    cuspPattern: "upper-molar",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: true,
    rootCurve: "away-from-midline",
  },
  17: {
    number: 17,
    displayName: "UR 2nd Molar",
    arch: "upper",
    side: "right",
    quadrant: "Q1",
    type: "molar",
    crownWidth: 1.1,
    crownHeight: 0.75,
    rootLength: 1.1,
    rootCount: 3,
    cuspCount: 4,
    cuspPattern: "upper-molar",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: true,
    rootCurve: "away-from-midline",
  },
  18: {
    number: 18,
    displayName: "UR Wisdom",
    arch: "upper",
    side: "right",
    quadrant: "Q1",
    type: "molar",
    crownWidth: 0.9,
    crownHeight: 0.7,
    rootLength: 1,
    rootCount: 2,
    cuspCount: 3,
    cuspPattern: "variable",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },

  // Q2 — upper left
  21: {
    number: 21,
    displayName: "UL Central",
    arch: "upper",
    side: "left",
    quadrant: "Q2",
    type: "incisor",
    crownWidth: 1,
    crownHeight: 1,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 0,
    cuspPattern: "smooth",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  22: {
    number: 22,
    displayName: "UL Lateral",
    arch: "upper",
    side: "left",
    quadrant: "Q2",
    type: "incisor",
    crownWidth: 0.85,
    crownHeight: 1,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 0,
    cuspPattern: "smooth",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  23: {
    number: 23,
    displayName: "UL Canine",
    arch: "upper",
    side: "left",
    quadrant: "Q2",
    type: "canine",
    crownWidth: 0.95,
    crownHeight: 1.1,
    rootLength: 1.4,
    rootCount: 1,
    cuspCount: 1,
    cuspPattern: "single-cusp",
    hasPointedCusp: true,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  24: {
    number: 24,
    displayName: "UL 1st PM",
    arch: "upper",
    side: "left",
    quadrant: "Q2",
    type: "premolar",
    crownWidth: 1,
    crownHeight: 0.9,
    rootLength: 1.2,
    rootCount: 2,
    cuspCount: 2,
    cuspPattern: "two-cusp",
    hasPointedCusp: false,
    hasTwoCusps: true,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  25: {
    number: 25,
    displayName: "UL 2nd PM",
    arch: "upper",
    side: "left",
    quadrant: "Q2",
    type: "premolar",
    crownWidth: 0.95,
    crownHeight: 0.9,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 2,
    cuspPattern: "two-cusp",
    hasPointedCusp: false,
    hasTwoCusps: true,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  26: {
    number: 26,
    displayName: "UL 1st Molar",
    arch: "upper",
    side: "left",
    quadrant: "Q2",
    type: "molar",
    crownWidth: 1.2,
    crownHeight: 0.8,
    rootLength: 1.1,
    rootCount: 3,
    cuspCount: 4,
    cuspPattern: "upper-molar",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: true,
    rootCurve: "away-from-midline",
  },
  27: {
    number: 27,
    displayName: "UL 2nd Molar",
    arch: "upper",
    side: "left",
    quadrant: "Q2",
    type: "molar",
    crownWidth: 1.1,
    crownHeight: 0.75,
    rootLength: 1.1,
    rootCount: 3,
    cuspCount: 4,
    cuspPattern: "upper-molar",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: true,
    rootCurve: "away-from-midline",
  },
  28: {
    number: 28,
    displayName: "UL Wisdom",
    arch: "upper",
    side: "left",
    quadrant: "Q2",
    type: "molar",
    crownWidth: 0.9,
    crownHeight: 0.7,
    rootLength: 1,
    rootCount: 2,
    cuspCount: 3,
    cuspPattern: "variable",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },

  // Q3 — lower left
  31: {
    number: 31,
    displayName: "LL Central",
    arch: "lower",
    side: "left",
    quadrant: "Q3",
    type: "incisor",
    crownWidth: 0.9,
    crownHeight: 0.9,
    rootLength: 1.1,
    rootCount: 1,
    cuspCount: 0,
    cuspPattern: "smooth",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  32: {
    number: 32,
    displayName: "LL Lateral",
    arch: "lower",
    side: "left",
    quadrant: "Q3",
    type: "incisor",
    crownWidth: 0.95,
    crownHeight: 0.9,
    rootLength: 1.1,
    rootCount: 1,
    cuspCount: 0,
    cuspPattern: "smooth",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  33: {
    number: 33,
    displayName: "LL Canine",
    arch: "lower",
    side: "left",
    quadrant: "Q3",
    type: "canine",
    crownWidth: 0.9,
    crownHeight: 1,
    rootLength: 1.3,
    rootCount: 1,
    cuspCount: 1,
    cuspPattern: "single-cusp",
    hasPointedCusp: true,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  34: {
    number: 34,
    displayName: "LL 1st PM",
    arch: "lower",
    side: "left",
    quadrant: "Q3",
    type: "premolar",
    crownWidth: 1,
    crownHeight: 0.85,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 2,
    cuspPattern: "two-cusp",
    hasPointedCusp: false,
    hasTwoCusps: true,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  35: {
    number: 35,
    displayName: "LL 2nd PM",
    arch: "lower",
    side: "left",
    quadrant: "Q3",
    type: "premolar",
    crownWidth: 0.95,
    crownHeight: 0.85,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 2,
    cuspPattern: "two-cusp",
    hasPointedCusp: false,
    hasTwoCusps: true,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  36: {
    number: 36,
    displayName: "LL 1st Molar",
    arch: "lower",
    side: "left",
    quadrant: "Q3",
    type: "molar",
    crownWidth: 1.3,
    crownHeight: 0.75,
    rootLength: 1.1,
    rootCount: 2,
    cuspCount: 5,
    cuspPattern: "lower-molar",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  37: {
    number: 37,
    displayName: "LL 2nd Molar",
    arch: "lower",
    side: "left",
    quadrant: "Q3",
    type: "molar",
    crownWidth: 1.2,
    crownHeight: 0.7,
    rootLength: 1.1,
    rootCount: 2,
    cuspCount: 4,
    cuspPattern: "lower-molar",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  38: {
    number: 38,
    displayName: "LL Wisdom",
    arch: "lower",
    side: "left",
    quadrant: "Q3",
    type: "molar",
    crownWidth: 0.9,
    crownHeight: 0.65,
    rootLength: 1,
    rootCount: 2,
    cuspCount: 3,
    cuspPattern: "variable",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },

  // Q4 — lower right
  41: {
    number: 41,
    displayName: "LR Central",
    arch: "lower",
    side: "right",
    quadrant: "Q4",
    type: "incisor",
    crownWidth: 0.9,
    crownHeight: 0.9,
    rootLength: 1.1,
    rootCount: 1,
    cuspCount: 0,
    cuspPattern: "smooth",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  42: {
    number: 42,
    displayName: "LR Lateral",
    arch: "lower",
    side: "right",
    quadrant: "Q4",
    type: "incisor",
    crownWidth: 0.95,
    crownHeight: 0.9,
    rootLength: 1.1,
    rootCount: 1,
    cuspCount: 0,
    cuspPattern: "smooth",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  43: {
    number: 43,
    displayName: "LR Canine",
    arch: "lower",
    side: "right",
    quadrant: "Q4",
    type: "canine",
    crownWidth: 0.9,
    crownHeight: 1,
    rootLength: 1.3,
    rootCount: 1,
    cuspCount: 1,
    cuspPattern: "single-cusp",
    hasPointedCusp: true,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  44: {
    number: 44,
    displayName: "LR 1st PM",
    arch: "lower",
    side: "right",
    quadrant: "Q4",
    type: "premolar",
    crownWidth: 1,
    crownHeight: 0.85,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 2,
    cuspPattern: "two-cusp",
    hasPointedCusp: false,
    hasTwoCusps: true,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  45: {
    number: 45,
    displayName: "LR 2nd PM",
    arch: "lower",
    side: "right",
    quadrant: "Q4",
    type: "premolar",
    crownWidth: 0.95,
    crownHeight: 0.85,
    rootLength: 1.2,
    rootCount: 1,
    cuspCount: 2,
    cuspPattern: "two-cusp",
    hasPointedCusp: false,
    hasTwoCusps: true,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  46: {
    number: 46,
    displayName: "LR 1st Molar",
    arch: "lower",
    side: "right",
    quadrant: "Q4",
    type: "molar",
    crownWidth: 1.3,
    crownHeight: 0.75,
    rootLength: 1.1,
    rootCount: 2,
    cuspCount: 5,
    cuspPattern: "lower-molar",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  47: {
    number: 47,
    displayName: "LR 2nd Molar",
    arch: "lower",
    side: "right",
    quadrant: "Q4",
    type: "molar",
    crownWidth: 1.2,
    crownHeight: 0.7,
    rootLength: 1.1,
    rootCount: 2,
    cuspCount: 4,
    cuspPattern: "lower-molar",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
  48: {
    number: 48,
    displayName: "LR Wisdom",
    arch: "lower",
    side: "right",
    quadrant: "Q4",
    type: "molar",
    crownWidth: 0.9,
    crownHeight: 0.65,
    rootLength: 1,
    rootCount: 2,
    cuspCount: 3,
    cuspPattern: "variable",
    hasPointedCusp: false,
    hasTwoCusps: false,
    hasMolarRidge: false,
    rootCurve: "away-from-midline",
  },
};

export function getOdontogramToothReference(toothNumber: number): OdontogramToothReference {
  const reference = TOOTH_REFERENCE[toothNumber];
  if (!reference) {
    throw new Error(`Unknown permanent FDI tooth number: ${toothNumber}`);
  }
  return reference;
}